name: event_listing_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.1
  flutter_screenutil: ^5.9.3
  lucide_icons: ^0.257.0
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  fpdart: ^1.1.1
  shimmer: ^3.0.0
  recase: ^4.1.0
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
    - family: JakartaBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf