// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR1rVxD_KnF4zgs5L0OzO1UEdXSvRlLXI',
    appId: '1:603057842547:android:0f33402daf7e7950107d06',
    messagingSenderId: '603057842547',
    projectId: 'alleventsapp-2f6d1',
    storageBucket: 'alleventsapp-2f6d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxD65LiTBzP4GFoCRjf6z9d5XfbXAIauE',
    appId: '1:603057842547:ios:a4c522c4f811d3d6107d06',
    messagingSenderId: '603057842547',
    projectId: 'alleventsapp-2f6d1',
    storageBucket: 'alleventsapp-2f6d1.firebasestorage.app',
    androidClientId: '603057842547-ot4045s55opn7q3euf7h1k6n3cagbuk2.apps.googleusercontent.com',
    iosClientId: '603057842547-ig3u49cdmih8t6pdlgbmla56jbp75jea.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventListingApp',
  );

}